// Code generated by Slice Machine. DO NOT EDIT.

import AboutSlice from './AboutSlice';
import AlbumsSlice from './AlbumsSlice';
import FooterSlice from './FooterSlice';
import NavSlice from './NavSlice';
import OpeningImgSlice from './OpeningImgSlice';
import PhotoGallerySlice from './PhotoGallerySlice';
import SubText from './SubText';

export {
	AboutSlice,
	AlbumsSlice,
	FooterSlice,
	NavSlice,
	OpeningImgSlice,
	PhotoGallerySlice,
	SubText,
};

export const components = {
	about_slice: AboutSlice,
	albums: AlbumsSlice,
	footer_slice: FooterSlice,
	nav_slice: NavSlice,
	opening_img: OpeningImgSlice,
	photo_gallery_slice: PhotoGallerySlice,
	sub_text: SubText,
};
